import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const permissionFile = join(process.cwd(), 'src-tauri', 'permissions', 'autogenerated.toml');

describe('Tauri command permissions', () => {
  it('allows the emulator root preflight scan command', () => {
    const permissions = readFileSync(permissionFile, 'utf8');

    expect(permissions).toContain('"scan_avd_root_readiness"');
  });
});
