/// <reference types="node" />

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

const permissionFile = join(process.cwd(), "src-tauri", "permissions", "autogenerated.toml");

describe("Tauri command permissions", () => {
  it("allows the emulator root preflight scan command", () => {
    const permissions = readFileSync(permissionFile, "utf-8");

    expect(permissions).toContain('"scan_avd_root_readiness"');
  });

  it("allows the emulator root verification command", () => {
    const permissions = readFileSync(permissionFile, "utf-8");

    expect(permissions).toContain('"verify_avd_root"');
  });

  it("allows scrcpy lifecycle commands", () => {
    const permissions = readFileSync(permissionFile, "utf-8");

    expect(permissions).toContain('"scrcpy_status"');
    expect(permissions).toContain('"scrcpy_check_update"');
    expect(permissions).toContain('"scrcpy_install"');
    expect(permissions).toContain('"scrcpy_uninstall"');
    expect(permissions).toContain('"scrcpy_launch"');
  });

  it("allows scrcpy session and preset commands", () => {
    const permissions = readFileSync(permissionFile, "utf-8");

    expect(permissions).toContain('"scrcpy_stop"');
    expect(permissions).toContain('"scrcpy_active_sessions"');
    expect(permissions).toContain('"scrcpy_presets"');
  });

  it("allows file explorer and editor commands", () => {
    const permissions = readFileSync(permissionFile, "utf-8");

    expect(permissions).toContain('"get_app_icons"');
    expect(permissions).toContain('"open_device_file_in_editor"');
    expect(permissions).toContain('"reveal_device_path_in_explorer"');
    expect(permissions).toContain('"transfer_device_files"');
    expect(permissions).toContain('"host_path_kinds"');
  });

  it("allows logcat, screenshot, and adb server commands", () => {
    const permissions = readFileSync(permissionFile, "utf-8");

    expect(permissions).toContain('"get_logcat_snapshot"');
    expect(permissions).toContain('"save_screenshot"');
    expect(permissions).toContain('"restart_adb_server"');
    expect(permissions).toContain('"kill_adb_server"');
    expect(permissions).toContain('"get_host_tool_versions"');
  });

  it("allows host setup commands", () => {
    const permissions = readFileSync(permissionFile, "utf-8");

    expect(permissions).toContain('"host_setup_status"');
    expect(permissions).toContain('"host_setup_install"');
    expect(permissions).toContain('"host_setup_install_driver"');
    expect(permissions).toContain('"launch_host_setup_terminal"');
    expect(permissions).toContain('"host_setup_repair_path"');
  });
});
