// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CleanupPayloadCache():Promise<void>;

export function ConnectWirelessAdb(arg1:string,arg2:string):Promise<string>;

export function DisconnectWirelessAdb(arg1:string,arg2:string):Promise<string>;

export function EnableWirelessAdb(arg1:string):Promise<string>;

export function ExtractPayload(arg1:string,arg2:string,arg3:Array<string>):Promise<backend.ExtractPayloadResult>;

export function FlashPartition(arg1:string,arg2:string):Promise<void>;

export function GetBootloaderVariables():Promise<string>;

export function GetDeviceInfo():Promise<backend.DeviceInfo>;

export function GetDeviceMode():Promise<string>;

export function GetDevices():Promise<Array<backend.Device>>;

export function GetFastbootDevices():Promise<Array<backend.Device>>;

export function GetInstalledPackages():Promise<Array<backend.InstalledPackage>>;

export function Greet(arg1:string):Promise<string>;

export function InstallPackage(arg1:string):Promise<string>;

export function LaunchDeviceManager():Promise<void>;

export function LaunchTerminal():Promise<void>;

export function ListFiles(arg1:string):Promise<Array<backend.FileEntry>>;

export function ListPayloadPartitions(arg1:string):Promise<Array<string>>;

export function ListPayloadPartitionsWithDetails(arg1:string):Promise<Array<backend.PartitionDetail>>;

export function OpenFolder(arg1:string):Promise<void>;

export function PullFile(arg1:string,arg2:string):Promise<string>;

export function PushFile(arg1:string,arg2:string):Promise<string>;

export function Reboot(arg1:string):Promise<void>;

export function RunAdbHostCommand(arg1:string):Promise<string>;

export function RunFastbootHostCommand(arg1:string):Promise<string>;

export function RunShellCommand(arg1:string):Promise<string>;

export function SaveLog(arg1:string,arg2:string):Promise<string>;

export function SelectApkFile():Promise<string>;

export function SelectDirectoryForPull():Promise<string>;

export function SelectDirectoryToPush():Promise<string>;

export function SelectFileToPush():Promise<string>;

export function SelectImageFile():Promise<string>;

export function SelectMultipleApkFiles():Promise<Array<string>>;

export function SelectOutputDirectory():Promise<string>;

export function SelectPayloadFile():Promise<string>;

export function SelectSaveDirectory(arg1:string):Promise<string>;

export function SelectZipFile():Promise<string>;

export function SetActiveSlot(arg1:string):Promise<void>;

export function SideloadPackage(arg1:string):Promise<string>;

export function UninstallPackage(arg1:string):Promise<string>;

export function WipeData():Promise<void>;
